# 01. Data-Setup

In [1]:
import os
import re
import pandas as pd
import numpy as np
from src.graph_theory import append_connectome_data

### Load Subject Information

In [2]:
data_path = os.getcwd() + "/data"
subdirectories = re.compile(r"^(ADNI|MUSC|TBI)-(.*)-n\d+$")

subject_info_df = pd.read_csv(data_path + "/subjects.csv")
subject_info_df.head()

,Subject,Study,Diagnosis,Analysis Group,PTSD status,Age (yrs),Sex,R1/R2 analysis complete?,Given to Konnor as of 11/6/23?,Comments
0,002_S_4225,ADNI,AD,AD,?,77.0,M,1,1,NaN
1,002_S_5018,ADNI,AD,AD,?,74.0,M,1,1,NaN
2,006_S_4153,ADNI,AD,AD,?,80.0,M,1,1,NaN
3,006_S_4192,ADNI,AD,AD,?,83.0,M,1,1,NaN
4,006_S_4546,ADNI,AD,AD,?,72.0,M,1,1,NaN

### Load Subject Data

In [3]:
# data directory has TBI/MUSC/ADNI subdirectories, POS/NEG each
#if "data_df" not in locals():
columns = ["Subject_ID", "Diagnosis", "Study", "Data"]
data_df = pd.DataFrame(columns=columns)

for root, dirs, files in os.walk(data_path):
    match = subdirectories.search(os.path.basename(root))
    if match:
        study = match.group(1)
        diagnosis = match.group(2)

        for file in files:
            if file.endswith(".csv") and file != "subjects.csv":
                file_path = os.path.join(root, file)

                subject_id_match = re.match(r"(.*)tts_all\.csv", file)
                if subject_id_match:
                    subject_id = subject_id_match.group(1)

                    data_matrix = pd.read_csv(file_path).values
                    new_row = {
                        "Subject_ID": subject_id.replace('_','').replace('-',''),
                        "Diagnosis": diagnosis,
                        "Study": study,
                        "Data": data_matrix,
                    }
                    data_df = pd.concat(
                        [data_df, pd.DataFrame([new_row])], ignore_index=True
                        )
data_df.head()

,Subject_ID,Diagnosis,Study,Data
0,1144,HC,MUSC,"[[58.73076183, 136.138853, 71.32999539, 41.065..."
1,1104,HC,MUSC,"[[12.18384103, -31.72224568, 11.98897454, 2.31..."
2,1085,HC,MUSC,"[[-1.300582984, -6.808979653, -28.1579185, 7.3..."
3,1051,HC,MUSC,"[[23.00822698, -126.074722, 77.52625116, 17.74..."
4,1155,HC,MUSC,"[[-6.295390793, -24.09210886, 31.53133265, -28..."

### Transform Subject Data into GT Metrics

- `data_df` and `subject_info_df` are of interest

In [4]:
data_df = append_connectome_data(data_df)
data_df.head()
data_df.to_pickle('data/data.pkl')

Row 1 of 228 (0.0%)
Row 2 of 228 (0.44%)
Row 3 of 228 (0.88%)
Row 4 of 228 (1.32%)
Row 5 of 228 (1.75%)
Row 6 of 228 (2.19%)
Row 7 of 228 (2.63%)
Row 8 of 228 (3.07%)
Row 9 of 228 (3.51%)
Row 10 of 228 (3.95%)
Row 11 of 228 (4.39%)
Row 12 of 228 (4.82%)
Row 13 of 228 (5.26%)
Row 14 of 228 (5.7%)
Row 15 of 228 (6.14%)
Row 16 of 228 (6.58%)
Row 17 of 228 (7.02%)
Row 18 of 228 (7.46%)
Row 19 of 228 (7.89%)
Row 20 of 228 (8.33%)
Row 21 of 228 (8.77%)
Row 22 of 228 (9.21%)
Row 23 of 228 (9.65%)
Row 24 of 228 (10.09%)
Row 25 of 228 (10.53%)
Row 26 of 228 (10.96%)
Row 27 of 228 (11.4%)
Row 28 of 228 (11.84%)
Row 29 of 228 (12.28%)
Row 30 of 228 (12.72%)
Row 31 of 228 (13.16%)
Row 32 of 228 (13.6%)
Row 33 of 228 (14.04%)
Row 34 of 228 (14.47%)
Row 35 of 228 (14.91%)
Row 36 of 228 (15.35%)
Row 37 of 228 (15.79%)
Row 38 of 228 (16.23%)
Row 39 of 228 (16.67%)
Row 40 of 228 (17.11%)
Row 41 of 228 (17.54%)
Row 42 of 228 (17.98%)
Row 43 of 228 (18.42%)
Row 44 of 228 (18.86%)
Row 45 of 228 (19.3%)
Row 46 of 228 (19.74%)
Row 47 of 228 (20.18%)
Row 48 of 228 (20.61%)
Row 49 of 228 (21.05%)
Row 50 of 228 (21.49%)
Row 51 of 228 (21.93%)
Row 52 of 228 (22.37%)
Row 53 of 228 (22.81%)
Row 54 of 228 (23.25%)
Row 55 of 228 (23.68%)
Row 56 of 228 (24.12%)
Row 57 of 228 (24.56%)
Row 58 of 228 (25.0%)
Row 59 of 228 (25.44%)
Row 60 of 228 (25.88%)
Row 61 of 228 (26.32%)
Row 62 of 228 (26.75%)
Row 63 of 228 (27.19%)
Row 64 of 228 (27.63%)
Row 65 of 228 (28.07%)
Row 66 of 228 (28.51%)
Row 67 of 228 (28.95%)
Row 68 of 228 (29.39%)
Row 69 of 228 (29.82%)
Row 70 of 228 (30.26%)
Row 71 of 228 (30.7%)
Row 72 of 228 (31.14%)
Row 73 of 228 (31.58%)
Row 74 of 228 (32.02%)
Row 75 of 228 (32.46%)
Row 76 of 228 (32.89%)
Row 77 of 228 (33.33%)
Row 78 of 228 (33.77%)
Row 79 of 228 (34.21%)
Row 80 of 228 (34.65%)
Row 81 of 228 (35.09%)
Row 82 of 228 (35.53%)
Row 83 of 228 (35.96%)
Row 84 of 228 (36.4%)
Row 85 of 228 (36.84%)
Row 86 of 228 (37.28%)
Row 87 of 228 (37.72%)
Row 88 of 228 (38.16%)
Row 89 of 228 (38.6%)
Row 90 of 228 (39.04%)
Row 91 of 228 (39.47%)
Row 92 of 228 (39.91%)
Row 93 of 228 (40.35%)
Row 94 of 228 (40.79%)
Row 95 of 228 (41.23%)
Row 96 of 228 (41.67%)
Row 97 of 228 (42.11%)
Row 98 of 228 (42.54%)
Row 99 of 228 (42.98%)
Row 100 of 228 (43.42%)
Row 101 of 228 (43.86%)
Row 102 of 228 (44.3%)
Row 103 of 228 (44.74%)
Row 104 of 228 (45.18%)
Row 105 of 228 (45.61%)
Row 106 of 228 (46.05%)
Row 107 of 228 (46.49%)
Row 108 of 228 (46.93%)
Row 109 of 228 (47.37%)
Row 110 of 228 (47.81%)
Row 111 of 228 (48.25%)
Row 112 of 228 (48.68%)
Row 113 of 228 (49.12%)
Row 114 of 228 (49.56%)
Row 115 of 228 (50.0%)
Row 116 of 228 (50.44%)
Row 117 of 228 (50.88%)
Row 118 of 228 (51.32%)
Row 119 of 228 (51.75%)
Row 120 of 228 (52.19%)
Row 121 of 228 (52.63%)
Row 122 of 228 (53.07%)
Row 123 of 228 (53.51%)
Row 124 of 228 (53.95%)
Row 125 of 228 (54.39%)
Row 126 of 228 (54.82%)
Row 127 of 228 (55.26%)
Row 128 of 228 (55.7%)
Row 129 of 228 (56.14%)
Row 130 of 228 (56.58%)
Row 131 of 228 (57.02%)
Row 132 of 228 (57.46%)
Row 133 of 228 (57.89%)
Row 134 of 228 (58.33%)
Row 135 of 228 (58.77%)
Row 136 of 228 (59.21%)
Row 137 of 228 (59.65%)
Row 138 of 228 (60.09%)
Row 139 of 228 (60.53%)
Row 140 of 228 (60.96%)
Row 141 of 228 (61.4%)
Row 142 of 228 (61.84%)
Row 143 of 228 (62.28%)
Row 144 of 228 (62.72%)
Row 145 of 228 (63.16%)
Row 146 of 228 (63.6%)
Row 147 of 228 (64.04%)
Row 148 of 228 (64.47%)
Row 149 of 228 (64.91%)
Row 150 of 228 (65.35%)
Row 151 of 228 (65.79%)
Row 152 of 228 (66.23%)
Row 153 of 228 (66.67%)
Row 154 of 228 (67.11%)
Row 155 of 228 (67.54%)
Row 156 of 228 (67.98%)
Row 157 of 228 (68.42%)
Row 158 of 228 (68.86%)
Row 159 of 228 (69.3%)
Row 160 of 228 (69.74%)
Row 161 of 228 (70.18%)
Row 162 of 228 (70.61%)
Row 163 of 228 (71.05%)
Row 164 of 228 (71.49%)
Row 165 of 228 (71.93%)
Row 166 of 228 (72.37%)
Row 167 of 228 (72.81%)
Row 168 of 228 (73.25%)
Row 169 of 228 (73.68%)
Row 170 of 228 (74.12%)
Row 171 of 228 (74.56%)
Row 172 of 228 (75.0%)
Row 173 of 228 (75.44%)
Row 174 of 228 (75.88%)
Row 175 of 228 (76.32%)
Row 176 of 228 (76.75%)
Row 177 of 228 (77.19%)
Row 178 of 228 (77.63%)
Row 179 of 228 (78.07%)
Row 180 of 228 (78.51%)
Row 181 of 228 (78.95%)
Row 182 of 228 (79.39%)
Row 183 of 228 (79.82%)
Row 184 of 228 (80.26%)
Row 185 of 228 (80.7%)
Row 186 of 228 (81.14%)
Row 187 of 228 (81.58%)
Row 188 of 228 (82.02%)
Row 189 of 228 (82.46%)
Row 190 of 228 (82.89%)
Row 191 of 228 (83.33%)
Row 192 of 228 (83.77%)
Row 193 of 228 (84.21%)
Row 194 of 228 (84.65%)
Row 195 of 228 (85.09%)
Row 196 of 228 (85.53%)
Row 197 of 228 (85.96%)
Row 198 of 228 (86.4%)
Row 199 of 228 (86.84%)
Row 200 of 228 (87.28%)
Row 201 of 228 (87.72%)
Row 202 of 228 (88.16%)
Row 203 of 228 (88.6%)
Row 204 of 228 (89.04%)
Row 205 of 228 (89.47%)
Row 206 of 228 (89.91%)
Row 207 of 228 (90.35%)
Row 208 of 228 (90.79%)
Row 209 of 228 (91.23%)
Row 210 of 228 (91.67%)
Row 211 of 228 (92.11%)
Row 212 of 228 (92.54%)
Row 213 of 228 (92.98%)
Row 214 of 228 (93.42%)
Row 215 of 228 (93.86%)
Row 216 of 228 (94.3%)
Row 217 of 228 (94.74%)
Row 218 of 228 (95.18%)
Row 219 of 228 (95.61%)
Row 220 of 228 (96.05%)
Row 221 of 228 (96.49%)
Row 222 of 228 (96.93%)
Row 223 of 228 (97.37%)
Row 224 of 228 (97.81%)
Row 225 of 228 (98.25%)
Row 226 of 228 (98.68%)
Row 227 of 228 (99.12%)
Row 228 of 228 (99.56%)